---
  el:
    hosts:
      centos8:
        ansible_connection: docker
  deb:
    hosts:
      ubuntu:
        ansible_connection: docker
  control_node:
    hosts:
      localhost:
        ansible_connection: local